FROM python:3.12-slim as base

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

WORKDIR /app

RUN --mount=type=bind,source=requirements-fastapi.txt,target=requirements-fastapi.txt \
    python -m pip install -r requirements-fastapi.txt

COPY /src/api/fastapi_nats.py .