FROM python:3.12-slim as base

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

WORKDIR /app

RUN --mount=type=bind,source=requirements-server.txt,target=requirements-server.txt \
    python -m pip install -r requirements-server.txt

COPY /src/api/fastapi_nats.py .
CMD python3 -m fastapi_nats run