"""rev_6: add metadata columns to events

Revision ID: 46179b928ef1
Revises: c81fd135fe13
Create Date: 2024-08-07 23:35:12.123456

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "46179b928ef1"
down_revision = "c81fd135fe13"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE ticket_status RENAME VALUE 'POSTPONED' TO 'MIGRATED'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE ticket_status RENAME VALUE 'MIGRATED' TO 'POSTPONED'")
    # ### end Alembic commands ###
