"""rev_3: add ticket enums and core event tables

Revision ID: 198ac35f2c79
Revises: fb82523175ba
Create Date: 2024-05-09 15:18:57.689138

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "198ac35f2c79"
down_revision = "fb82523175ba"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "base_tickets",
        sa.Column("flag_individual", sa.Boolean()),
    )
    op.add_column(
        "base_tickets",
        sa.Column("flag_season_ticket", sa.Boolean()),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("base_tickets", "flag_season_ticket")
    op.drop_column("base_tickets", "flag_individual")
    # ### end Alembic commands ###
