"""Added account table

Revision ID: c437c83dc576
Revises: 
Create Date: 2024-01-12 23:33:59.055094

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'c437c83dc576'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('theater_events',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.PrimaryKeyConstraint('id',
                                            name=op.f('pk__theater_events'))
                    )
    op.create_table('users',
                    sa.Column('id', sa.BigInteger(), autoincrement=False,
                              nullable=False),
                    sa.Column('callback_name', sa.String(), nullable=False),
                    sa.Column('callback_phone', sa.String(), nullable=True),
                    sa.Column('created_at', sa.TIMESTAMP(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', sa.TIMESTAMP(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk__users')),
                    sa.UniqueConstraint('id', name=op.f('uq__users__id'))
                    )
    op.create_table('children',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(), nullable=True),
                    sa.Column('user_id', sa.BigInteger(), nullable=False),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'],
                                            name=op.f(
                                                'fk__children__user_id__users')),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk__children'))
                    )
    op.create_table('tickets',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.BigInteger(), nullable=False),
                    sa.Column('theater_event_id', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.TIMESTAMP(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', sa.TIMESTAMP(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.ForeignKeyConstraint(['theater_event_id'],
                                            ['theater_events.id'], name=op.f(
                            'fk__tickets__theater_event_id__theater_events')),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'],
                                            name=op.f(
                                                'fk__tickets__user_id__users')),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk__tickets'))
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tickets')
    op.drop_table('children')
    op.drop_table('users')
    op.drop_table('theater_events')
    # ### end Alembic commands ###
