"""rev_1: add user preferences and update children age nullable

Revision ID: 0cfd834f030e
Revises: 31c46999db1a
Create Date: 2024-04-07 14:19:58.000000

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "0cfd834f030e"
down_revision = "31c46999db1a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "children",
        "age",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=True,
    )
    op.add_column(
        "users", sa.Column("agreement_received", sa.Date(), nullable=True)
    )
    op.add_column(
        "users", sa.Column("is_privilege", sa.Boolean(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "is_privilege")
    op.drop_column("users", "agreement_received")
    op.alter_column(
        "children",
        "age",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=False,
    )
    # ### end Alembic commands ###
