"""rev7

Revision ID: 83d1fd16082b
Revises: 46179b928ef1
Create Date: 2024-10-13 15:48:48.036202

"""

from alembic import op
import sqlalchemy as sa

from db import BaseModel

# revision identifiers, used by Alembic.
revision = "83d1fd16082b"
down_revision = "46179b928ef1"
branch_labels = None
depends_on = None

CustomMadeStatus = sa.Enum(
    "CREATED",
    "APPROVED",
    "PREPAID",
    "PAID",
    "REJECTED",
    "REFUNDED",
    "CANCELED",
    name="custom_made_status",
    metadata=BaseModel.metadata
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    CustomMadeStatus.create(op.get_bind(), checkfirst=True)
    op.create_table(
        "custom_made_formats",
        sa.Column("id", sa.BIGINT(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("price", sa.BIGINT(), nullable=False),
        sa.Column("flag_outside", sa.BOOLEAN(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__custom_made_formats")),
    )
    op.create_table(
        "custom_made_events",
        sa.Column("id", sa.BIGINT(), nullable=False),
        sa.Column("place", sa.BIGINT(), nullable=False),
        sa.Column("address", sa.String(), nullable=False),
        sa.Column("date", sa.String(), nullable=False),
        sa.Column("time", sa.String(), nullable=False),
        sa.Column("age", sa.Float()),
        sa.Column("qty_child", sa.BIGINT(), nullable=False),
        sa.Column("qty_adult", sa.BIGINT(), nullable=False),
        sa.Column("name_child", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("phone", sa.String(), nullable=False),
        sa.Column("note", sa.String()),
        sa.Column("status", CustomMadeStatus, nullable=False),
        sa.Column("user_id", sa.BigInteger()),
        sa.Column("custom_made_format_id", sa.BIGINT(), nullable=False),
        sa.Column("theater_event_id", sa.BIGINT()),
        sa.Column("ticket_id", sa.BIGINT()),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["custom_made_format"],
            ["custom_made_formats.id"],
            name=op.f(
                "fk__custom_made_events__custom_made_format_id__custom_made_formats"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["theater_event_id"],
            ["theater_events.id"],
            name=op.f(
                "fk__custom_made_events__theater_event_id__theater_events"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["ticket_id"],
            ["tickets.id"],
            name=op.f("fk__custom_made_events__ticket_id__tickets"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.user_id"],
            name=op.f("fk__custom_made_events__user_id__users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__custom_made_events")),
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("custom_made_events")
    op.drop_table("custom_made_formats")
    CustomMadeStatus.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
