"""rev_4_add_base_tickets_type_events

Revision ID: 3302b537affc
Revises: 198ac35f2c79
Create Date: 2024-05-12 21:57:42.423417

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "3302b537affc"
down_revision = "198ac35f2c79"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "base_tickets_type_events",
        sa.Column("base_ticket_id", sa.BIGINT(), nullable=False),
        sa.Column("type_event_id", sa.BIGINT(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["base_ticket_id"],
            ["base_tickets.base_ticket_id"],
            name=op.f(
                "fk__base_tickets_type_events__base_ticket_id__base_tickets"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["type_event_id"],
            ["type_events.id"],
            name=op.f(
                "fk__base_tickets_type_events__type_event_id__type_events"
            ),
        ),
        sa.PrimaryKeyConstraint(
            "base_ticket_id",
            "type_event_id",
            name=op.f("pk__base_tickets_type_events"),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("base_tickets_type_events")
    # ### end Alembic commands ###
