"""rev_2: add base_tickets relations

Revision ID: fb82523175ba
Revises: 0cfd834f030e
Create Date: 2024-05-05 12:54:09.777192

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "fb82523175ba"
down_revision = "0cfd834f030e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "base_tickets_theater_events",
        sa.Column("base_ticket_id", sa.BIGINT(), nullable=False),
        sa.Column("theater_event_id", sa.BIGINT(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["base_ticket_id"],
            ["base_tickets.base_ticket_id"],
            name=op.f(
                "fk__base_tickets_theater_events__base_ticket_id__base_tickets"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["theater_event_id"],
            ["theater_events.id"],
            name=op.f(
                "fk__base_tickets_theater_events__theater_event_id__theater_events"
            ),
        ),
        sa.PrimaryKeyConstraint(
            "base_ticket_id",
            "theater_event_id",
            name=op.f("pk__base_tickets_theater_events"),
        ),
    )
    op.create_table(
        "base_tickets_schedule_events",
        sa.Column("base_ticket_id", sa.BIGINT(), nullable=False),
        sa.Column("schedule_event_id", sa.BIGINT(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["base_ticket_id"],
            ["base_tickets.base_ticket_id"],
            name=op.f(
                "fk__base_tickets_schedule_events__base_ticket_id__base_tickets"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["schedule_event_id"],
            ["schedule_events.id"],
            name=op.f(
                "fk__base_tickets_schedule_events__schedule_event_id__schedule_events"
            ),
        ),
        sa.PrimaryKeyConstraint(
            "base_ticket_id",
            "schedule_event_id",
            name=op.f("pk__base_tickets_schedule_events"),
        ),
    )
    op.add_column(
        "theater_events", sa.Column("duration", sa.Time(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("theater_events", "duration")
    op.drop_table("base_tickets_schedule_events")
    op.drop_table("base_tickets_theater_events")
    # ### end Alembic commands ###
