"""rev10

Revision ID: cedbea3f6c04
Revises: c9f1e5a9f1a2
Create Date: 2025-11-30 21:31:40.865207

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "cedbea3f6c04"
down_revision = "c9f1e5a9f1a2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sales_campaigns",
        sa.Column("id", sa.BIGINT(), nullable=False),
        sa.Column("created_by_admin_id", sa.BigInteger(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("theater_event_id", sa.BIGINT(), nullable=False),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("message_kind", sa.String(), nullable=True),
        sa.Column("message_text", sa.String(), nullable=True),
        sa.Column("message_entities", sa.JSON(), nullable=True),
        sa.Column("caption_text", sa.String(), nullable=True),
        sa.Column("caption_entities", sa.JSON(), nullable=True),
        sa.Column("photo_file_id", sa.String(), nullable=True),
        sa.Column("video_file_id", sa.String(), nullable=True),
        sa.Column("animation_file_id", sa.String(), nullable=True),
        sa.Column("extra_payload", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["theater_event_id"],
            ["theater_events.id"],
            name=op.f("fk__sales_campaigns__theater_event_id__theater_events"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__sales_campaigns")),
    )
    op.create_table(
        "sales_campaign_schedules",
        sa.Column("id", sa.BIGINT(), nullable=False),
        sa.Column("campaign_id", sa.BIGINT(), nullable=False),
        sa.Column("schedule_event_id", sa.BIGINT(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["sales_campaigns.id"],
            name=op.f(
                "fk__sales_campaign_schedules__campaign_id__sales_campaigns"
            ),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["schedule_event_id"],
            ["schedule_events.id"],
            name=op.f(
                "fk__sales_campaign_schedules__schedule_event_id__schedule_events"
            ),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "id", name=op.f("pk__sales_campaign_schedules")
        ),
        sa.UniqueConstraint(
            "campaign_id",
            "schedule_event_id",
            name=op.f(
                "uq__sales_campaign_schedules__campaign_id_schedule_event_id"
            ),
        ),
    )
    op.create_table(
        "sales_recipients",
        sa.Column("id", sa.BIGINT(), nullable=False),
        sa.Column("campaign_id", sa.BIGINT(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=True),
        sa.Column("chat_id", sa.BigInteger(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("last_error", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["sales_campaigns.id"],
            name=op.f("fk__sales_recipients__campaign_id__sales_campaigns"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.user_id"],
            name=op.f("fk__sales_recipients__user_id__users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__sales_recipients")),
        sa.UniqueConstraint(
            "campaign_id",
            "chat_id",
            name=op.f("uq__sales_recipients__campaign_id_chat_id"),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("sales_recipients")
    op.drop_table("sales_campaign_schedules")
    op.drop_table("sales_campaigns")
    # ### end Alembic commands ###
