"""rev_8: add age limits and emoji to events

Revision ID: 06fcbbb514eb
Revises: 83d1fd16082b
Create Date: 2025-02-13 22:05:12.123456

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "06fcbbb514eb"
down_revision = "83d1fd16082b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "theater_events", sa.Column("note", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("theater_events", "note")
    # ### end Alembic commands ###
