"""rev_24_add_places_model

Revision ID: f8a2b3c4d5e6
Revises: ac6b69749afa
Create Date: 2026-09-18 14:30:00.000000

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f8a2b3c4d5e6"
down_revision = "ac6b69749afa"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "places",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("address", sa.Text(), nullable=False),
        sa.Column("link_on_yndx_maps", sa.String(), nullable=True),
        sa.Column("link_about", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__places")),
    )
    op.add_column("schedule_events", sa.Column("place_id", sa.BIGINT(), nullable=True))
    op.create_index(op.f("ix__schedule_events__place_id"), "schedule_events", ["place_id"], unique=False)
    op.create_foreign_key(op.f("fk__schedule_events__place_id__places"), "schedule_events", "places", ["place_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk__schedule_events__place_id__places"), "schedule_events", type_="foreignkey")
    op.drop_index(op.f("ix__schedule_events__place_id"), table_name="schedule_events")
    op.drop_column("schedule_events", "place_id")
    op.drop_table("places")
    # ### end Alembic commands ###
