"""add_tg_updates_table

Revision ID: 105f2aad266f
Revises: e7135eecdea0
Create Date: 2026-01-25 12:53:36.919987

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "105f2aad266f"
down_revision = "e7135eecdea0"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tg_updates",
        sa.Column("id", sa.BIGINT(), nullable=False),
        sa.Column("update_id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=True),
        sa.Column("chat_id", sa.BigInteger(), nullable=True),
        sa.Column("text", sa.String(), nullable=True),
        sa.Column("message_id", sa.BigInteger(), nullable=True),
        sa.Column("reply_to_message_id", sa.BigInteger(), nullable=True),
        sa.Column("message_thread_id", sa.BigInteger(), nullable=True),
        sa.Column("message", sa.JSON(), nullable=True),
        sa.Column("edited_message", sa.JSON(), nullable=True),
        sa.Column("channel_post", sa.JSON(), nullable=True),
        sa.Column("edited_channel_post", sa.JSON(), nullable=True),
        sa.Column("inline_query", sa.JSON(), nullable=True),
        sa.Column("chosen_inline_result", sa.JSON(), nullable=True),
        sa.Column("callback_query", sa.JSON(), nullable=True),
        sa.Column("shipping_query", sa.JSON(), nullable=True),
        sa.Column("pre_checkout_query", sa.JSON(), nullable=True),
        sa.Column("poll", sa.JSON(), nullable=True),
        sa.Column("poll_answer", sa.JSON(), nullable=True),
        sa.Column("my_chat_member", sa.JSON(), nullable=True),
        sa.Column("chat_member", sa.JSON(), nullable=True),
        sa.Column("chat_join_request", sa.JSON(), nullable=True),
        sa.Column("chat_boost", sa.JSON(), nullable=True),
        sa.Column("removed_chat_boost", sa.JSON(), nullable=True),
        sa.Column("message_reaction", sa.JSON(), nullable=True),
        sa.Column("message_reaction_count", sa.JSON(), nullable=True),
        sa.Column("business_connection", sa.JSON(), nullable=True),
        sa.Column("business_message", sa.JSON(), nullable=True),
        sa.Column("edited_business_message", sa.JSON(), nullable=True),
        sa.Column("deleted_business_messages", sa.JSON(), nullable=True),
        sa.Column("purchased_paid_media", sa.JSON(), nullable=True),
        sa.Column("full_update", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__tg_updates")),
        sa.UniqueConstraint(
            "update_id", name=op.f("uq__tg_updates__update_id")
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tg_updates")
    # ### end Alembic commands ###
