"""rev_22_add_special_ticket_prices

Revision ID: b52e184f475a
Revises: 8a737ab30cd0
Create Date: 2026-03-28 21:00:00.000000

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b52e184f475a"
down_revision = "8a737ab30cd0"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "special_ticket_prices",
        sa.Column("id", sa.BIGINT(), nullable=False),
        sa.Column("option", sa.String(length=255), nullable=False),
        sa.Column("base_ticket_id", sa.BIGINT(), nullable=False),
        sa.Column("price_weekday", sa.BIGINT(), nullable=True),
        sa.Column("price_weekend", sa.BIGINT(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["base_ticket_id"],
            ["base_tickets.base_ticket_id"],
            name=op.f(
                "fk__special_ticket_prices__base_ticket_id__base_tickets"
            ),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__special_ticket_prices")),
        sa.UniqueConstraint(
            "option", "base_ticket_id", name="uq_option_base_ticket"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("special_ticket_prices")
    # ### end Alembic commands ###
