"""rev_18_add parent_id to people

Revision ID: c427f0da1b22
Revises: 8d8e8b8c8a89
Create Date: 2026-02-20 10:22:05.324424

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c427f0da1b22"
down_revision = "8d8e8b8c8a89"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "bot_settings",
        "id",
        existing_type=sa.INTEGER(),
        type_=sa.BIGINT(),
        existing_nullable=False,
        autoincrement=True,
    )
    op.add_column("people", sa.Column("parent_id", sa.BIGINT(), nullable=True))
    op.create_foreign_key(
        op.f("fk__people__parent_id__people"),
        "people",
        "people",
        ["parent_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk__people__parent_id__people"), "people", type_="foreignkey"
    )
    op.drop_column("people", "parent_id")
    op.alter_column(
        "bot_settings",
        "id",
        existing_type=sa.BIGINT(),
        type_=sa.INTEGER(),
        existing_nullable=False,
        autoincrement=True,
    )
    # ### end Alembic commands ###
