"""add promocode fields

Revision ID: c00ba0fb22b5
Revises: 105f2aad266f
Create Date: 2026-02-04 20:00:47.571314

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "c00ba0fb22b5"
down_revision = "105f2aad266f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "promotions",
        sa.Column(
            "discount_type",
            sa.Enum("percentage", "fixed", name="promotiondiscounttype"),
            nullable=False,
        ),
    )
    op.add_column(
        "promotions",
        sa.Column("is_visible_as_option", sa.Boolean(), nullable=False),
    )
    op.add_column(
        "promotions",
        sa.Column("min_purchase_sum", sa.BIGINT(), nullable=False),
    )
    op.add_column(
        "promotions", sa.Column("description_user", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("promotions", "description_user")
    op.drop_column("promotions", "min_purchase_sum")
    op.drop_column("promotions", "is_visible_as_option")
    op.drop_column("promotions", "discount_type")
    # ### end Alembic commands ###
