"""rev_23_add_Afisha_model

Revision ID: ac6b69749afa
Revises: b52e184f475a
Create Date: 2026-05-03 21:56:27.575786

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ac6b69749afa"
down_revision = "b52e184f475a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "afishas",
        sa.Column("id", sa.BIGINT(), nullable=False),
        sa.Column("month", sa.BIGINT(), nullable=False),
        sa.Column("year", sa.BIGINT(), nullable=False),
        sa.Column("file_id", sa.String(), nullable=False),
        sa.Column("file_path", sa.String(), nullable=False),
        sa.Column("zones", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__afishas")),
        sa.UniqueConstraint("month", "year", name="uq_afisha_month_year"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("afishas")
    # ### end Alembic commands ###
