"""rev_14_add_promocode_fields_and_verification

Revision ID: c00ba0fb22b5
Revises: 7a9b2c1d3e4f
Create Date: 2026-02-04 20:00:47.571314

"""

from alembic import op
import sqlalchemy as sa

from db import BaseModel

# revision identifiers, used by Alembic.
revision = "c00ba0fb22b5"
down_revision = "7a9b2c1d3e4f"
branch_labels = None
depends_on = None

PromotionDiscountTypeEnum = sa.Enum(
    "percentage",
    "fixed",
    name="promotiondiscounttype",
    metadata=BaseModel.metadata
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    PromotionDiscountTypeEnum.create(op.get_bind(), checkfirst=True)
    op.add_column(
        "promotions",
        sa.Column(
            "discount_type",
            PromotionDiscountTypeEnum,
            nullable=False,
            server_default="fixed",
        ),
    )
    op.add_column(
        "promotions",
        sa.Column("is_visible_as_option",
                  sa.Boolean(),
                  nullable=False,
                  server_default="false"),
    )
    op.add_column(
        "promotions",
        sa.Column("min_purchase_sum", sa.BIGINT(), nullable=False, server_default="0"),
    )
    op.add_column(
        "promotions", sa.Column("description_user", sa.String(), nullable=True)
    )
    op.add_column(
        "promotions",
        sa.Column(
            "requires_verification",
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("false"),
        ),
    )
    op.add_column(
        "promotions",
        sa.Column("verification_text", sa.String(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("promotions", "verification_text")
    op.drop_column("promotions", "requires_verification")
    op.drop_column("promotions", "description_user")
    op.drop_column("promotions", "min_purchase_sum")
    op.drop_column("promotions", "is_visible_as_option")
    op.drop_column("promotions", "discount_type")
    PromotionDiscountTypeEnum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
