birthday_data = {
        'place': 'Место',
        'address': 'Адрес',
        'date': 'Дата',
        'time': 'Время',
        'theater_event_id': 'Спектакль',
        'age': 'Возраст именинника',
        'qty_child': 'Кол-во детей',
        'qty_adult': 'Кол-во взрослых',
        'custom_made_format_id': 'Формат праздника',
        'name_child': 'Имя именинника',
        'name': 'Контактное лицо',
        'phone': 'Контактный телефон',
        'note': 'Примечание',
    }
